### ISSUE TITLE
Buttons translation

### ISSUE THREAD

**Issue by themelisx** [IvanKovac/TimePickerWithSeconds#6]
Is it possible to add translation for buttons (text) ?
Or is it possible to set the text programmatically?

If you want to add translation into values, for Greek language the translation (values-el) is below:

<string name="action_settings">Ρυθμίσεις</string>
<string name="time_set">Ορισμός</string>
<string name="cancel">Ακύρωση</string>
<string name="time">Ώρα : </string>

Thanks anyway

**Comment by IvanKovac** [comment]
Yes it is possible. Can you make the code changes and create a pull request? Like this one:
https://github.com/IvanKovac/TimePickerWithSeconds/commit/8840352ac94a08de71cc58d3b999d445ac0a7372
