### ISSUE TITLE
Using APK from gradle says the min SDK is 15 but in the repo it is 11

### ISSUE THREAD

**Issue by Max-Might** [IvanKovac/TimePickerWithSeconds#7]
Hi.

I have added the project using gradle to my project as shown in the README file.
Gradle stops the compilation saying the project requires min sdk level 15 but my project is 14.

```
uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.kovachcode:timePickerWithSeconds:1.0.1]
```

Is the APK uploaded in the repo updated after the min sdk was set to 11?

**Comment by IvanKovac** [comment]
Problem is happening because google has changed minimum sdk version for their support library which is used in this project, so gradle file automatically change minimum sdk to that version.

Cannot promise that we will solve this issue in fast manner.
